# Dependencies
highligther:         true

# Gems
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# Setup
title:            Yagya's Pages
tagline:          'learning never ends'

paginate:         5

# Custom vars
version:          2.0.0

# Analytics
google_analytics: UA-93374633-1
